sonar.projectKey=sorravitsis_Online
sonar.organization=sorravitsis

sonar.projectName=Online AWB Platform
sonar.projectVersion=1.0

sonar.sources=.
sonar.exclusions=**/.next/**,**/node_modules/**,**/coverage/**,**/*.test.*,**/tests/**,**/*.config.*,**/public/**,**/docs/**,**/supabase/**

sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.typescript.tsconfigPath=tsconfig.json

sonar.language=ts,js
