uploads = []
outputs = []

[[generated]]
id = "oEjcnO2vIG59bsdg6Yfls"
uri = "file://attached_assets/logitech_mouse.png"
type = "image"
title = "logitech mx master mouse"

[[generated]]
id = "yraOyJnKMWNWlC0WWEw8p"
uri = "file://attached_assets/logitech_keyboard.png"
type = "image"
title = "logitech mx keys keyboard"

[[generated]]
id = "9GnFdadttw0K91b-aYcjs"
uri = "file://attached_assets/logitech_webcam.png"
type = "image"
title = "logitech brio webcam"

[[generated]]
id = "o4rKeYmtc-nJjdR1GGHlI"
uri = "file://attached_assets/logitech_headset.png"
type = "image"
title = "logitech headset"

[[generated]]
id = "kv_Eomdo7Is8R1krPVaMn"
uri = "file://attached_assets/asus_notebook.png"
type = "image"
title = "asus notebook laptop"

[[generated]]
id = "5VFkZo5ex4uwzxDOdi_Jf"
uri = "file://attached_assets/xiaomi_devices.png"
type = "image"
title = "xiaomi smart devices"

[[generated]]
id = "w66ZPbMS_iL9zOTjVKPTw"
uri = "file://attached_assets/logo_logitech.png"
type = "image"
title = "logitech logo"

[[generated]]
id = "9PKb2_eLzwY7ZeCXVj0U6"
uri = "file://attached_assets/logo_xiaomi.png"
type = "image"
title = "xiaomi logo"

[[generated]]
id = "GzAAcgCigmrNk6vXDPk9O"
uri = "file://attached_assets/logo_asus.png"
type = "image"
title = "asus logo"

[[generated]]
id = "PE7fKu4fgQRAK7xJbrA-W"
uri = "file://attached_assets/logo_brother.png"
type = "image"
title = "brother logo"
